blog/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.utils.functional import lazy

from djblogkit.blog.models import Entry, Archive, Comment, Trackback, Tag
from djblogkit.blog.feeds import DjblogkitRss

feeds = {
    'rss': DjblogkitRss
}
tag_feeds = {
    'rss': DjblogkitRss
}

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.list_detail.object_list', dict(queryset=Entry.public_objects.all().select_related(), paginate_by=settings.NUM_IN_PAGE, allow_empty=True)),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>.*)/add_comment/$', 'djblogkit.blog.views.add_comment',),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>.*)/tbping/$', 'djblogkit.blog.views.tbping',),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>.*)/$', 'django.views.generic.date_based.object_detail', dict(queryset=Entry.public_objects.all().select_related(), date_field='create_date', slug_field='slug')),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', 'django.views.generic.date_based.archive_day', dict(queryset=Entry.public_objects.all().select_related(), date_field='create_date')),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', 'django.views.generic.date_based.archive_month', dict(queryset=Entry.public_objects.all().select_related(), date_field='create_date')),
    (r'^tag/(?P<tag>.*)/$', 'djblogkit.blog.views.tag_list'),
    (r'^related/search/(?P<content_type_id>\d+)/(?P<object_id>\d+)/(?P<target_content_type_id>\d+)/$', 'djblogkit.blog.views.pickup_related_items'),
    (r'^related/current/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', 'djblogkit.blog.views.current_related_items'),
    (r'^related/add/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', 'djblogkit.blog.views.add_related_item'),
    (r'^related/remove/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$', 'djblogkit.blog.views.remove_related_item'),
    #RSS
    #url must be rss
    (r'^feed/(?P<url>.*)/(?P<tag>.*)/$', 'djblogkit.blog.views.tag_feed'),
    (r'^feed/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),

)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^djblogkit/', include('djblogkit.blog.urls')),
    (r'^admin/(.*)', admin.site.root),
)

blog/models.py
from django.db import models
from django.db.models.query import Q
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.core.validators import ValidationError
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader, Context, TemplateDoesNotExist 
from django.utils.translation import gettext_lazy as _
from django.contrib import admin

import os

default_related_template = os.path.join(os.path.join('blog', 'related'), 'object.html')
def render_related_obejct(related_object):
    template_name = os.path.join(os.path.join('blog', 'related'), related_object.t)
    try:
        template = loader.get_template(template_name)
    except TemplateDoesNotExist:
        template = loader.get_template(default_related_template)
    context = Context({'related_object':related_object})
    return template.render(context)
 
def delete_for_related(related_object):
    ms = related_object.get_content_type()
    RelatedItem.objects.filter((Q(content_type__exact=ms.id) & Q(object_id__exact=related_object.id)) | (Q(related_content_type__exact=ms.id) & Q(related_object_id__exact=related_object.id))).delete()
    super(related_object.__class__, related_object).delete()

class RelatedItem(models.Model) :
    content_type = models.ForeignKey(ContentType, verbose_name=_('Main Content Type'), related_name='relateditem_as_main_set')
    object_id = models.IntegerField(_('main object ID'))
    related_content_type = models.ForeignKey(ContentType, verbose_name=_('Related Content Type'), related_name='relateditem_as_related_set')
    related_object_id = models.IntegerField(_('related object ID'))
    pub_date = models.DateTimeField(auto_now_add=True)

    main_object = generic.GenericForeignKey()
    related_object = generic.GenericForeignKey(ct_field='related_content_type', fk_field='related_object_id')

    unique_together = (('content_type', 'object_id', 'related_content_type', 'related_object_id'), )

    inline = False

    def get_object(self):
        try:
            return self.content_type.get_object_for_this_type(pk=self.object_id)
        except ObjectDoesNotExist:
            return None

    def get_related_object(self):
        try:
            return self.related_content_type.get_object_for_this_type(pk=self.related_object_id)
        except ObjectDoesNotExist:
            return None

    def __unicode__(self) :
        return u'%s:%s-%s:%s' % (self.content_type, self.object_id, self.related_content_type, self.related_object_id)

    def delete(self):
        super(RelatedItem, self).delete()
        try :
            exist_item = RelatedItem.objects.get(content_type=self.related_content_type, object_id=self.related_object_id,
                                                related_content_type=self.content_type, related_object_id=self.object_id)
        except ObjectDoesNotExist:
            pass
        else:
            exist_item.delete()

class RelatedModelBase(object):
    inline = False
    t = ''
    myself = None

    related_contents = generic.GenericRelation(RelatedItem)

    def as_list(self) :
        return self.__unicode__()

    def get_content_type(self):
        if not self.__class__.myself:
            self.__class__.myself = ContentType.objects.get_for_model(self.__class__)
        return self.__class__.myself

    def _add_script(self):
        return "javascript:set_related('%d','%d');return false;" % (self.get_content_type().id, self.id)

    def _del_script(self):
        return "javascript:remove_related('%d','%d');return false;" % (self.get_content_type().id, self.id)

    def _render_related(self):
        return render_related_obejct(self)
    render_related = property(_render_related)

    def render_as_add_list(self):
        return '''<div class="related_search_result" id="related_search_result_%d_%d">
<div class="related_action"><a href="#" onClick="%s"><img class="add_icon" width="24" height="24" /></a></div>
<div class="related_title">%s</div>
<div class="dummy"></div>
</div>
'''  % (self.get_content_type().id, self._get_pk_val(), self._add_script() , self.as_list(), )

    def render_as_del_list(self):
        return '''<div class="related_current_result" id="related_current_result_%d_%d">
<div class="related_action"><a href="#" onClick="%s"><img class="del_icon" width="24" height="24" /></a></div>
<div class="related_title">%s</div>
<div class="dummy"></div>
</div>
''' % (self.get_content_type().id, self._get_pk_val(), self._del_script() , self.as_list(), )

def is_relatable(field_data, all_data):
    c = ContentType.objects.get(pk=field_data).model_class()
    if not issubclass(c, RelatedModelBase):
        raise ValidationError, _("You must select Only Relatable Model(%s isn't)" % c._meta.object_name)

class Relatable(models.Model):
    content_type = models.ForeignKey(ContentType, verbose_name=_('Selected Related Model'), unique=True, validator_list=[is_relatable])

    def __unicode__(self):
        return self.content_type.name

class Archive(models.Model) :
    yearmonth = models.CharField(max_length=6, blank=False)
    ym_dict = {'01': 'jan','02': 'feb','03': 'mar',
               '04': 'apr','05': 'may','06': 'jun',
               '07': 'jul','08': 'aug','09': 'sep',
               '10': 'oct','11': 'nov','12': 'dec',}

    def __unicode__(self) :
        return self.yearmonth

    def _year(self) :
        return self.yearmonth[:4]
    year = property(_year)

    def _month(self):
        return self.yearmonth[4:6]
    month = property(_month)

    def get_path(self) :
        month = ''
        year = self.yearmonth[0:4]
        mm = self.yearmonth[4:6]
        month = Archive.ym_dict[mm]
        return '%s/%s/%s/' % (settings.BLOG_BASE, year, month)
    path = property(get_path)

    def get_absolute_url(self) :
        return self.get_path()
    absolute_url = property(get_absolute_url)

class Tag(models.Model) :
    create_date = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=25, unique=True, blank=False)

    def __unicode__(self) :
        return self.name

    def get_absolute_url(self) :
        return '%s/tag/%s/' % (settings.BLOG_BASE, self.name)
    absolute_url = property(get_absolute_url)


class EntryPublicManager(models.Manager) :
    def get_query_set(self) :
        return super(EntryPublicManager, self).get_query_set().filter(visible=True)

class EntryPrivateManager(models.Manager) :
    pass

class Entry(models.Model, RelatedModelBase) :
    title = models.CharField(_('Title'), max_length=250, blank=False)
    author = models.ForeignKey(User, verbose_name=_('Author'))
    slug = models.SlugField(_('Slug'), unique_for_date='create_date', help_text=_('Use for url. You hova to input yourself if your title is not Ascii Charcters.'))
    summary = models.TextField(_('Summary'), blank=False)
    body = models.TextField(_('Body'), blank=True)
    create_date = models.DateTimeField(_('Create date'), auto_now_add=True, editable=False)
    update_date = models.DateTimeField(_('Update date'), auto_now=True, editable=False)
    visible = models.BooleanField(default=True, help_text=_('Show this entry for only logined user.'))
    ping_now = models.BooleanField(default=False, help_text=_("Ping entry info for ping sites. Attn, it doesn't work if Entry is not visible."))

    trackback_now = models.BooleanField(default=False, help_text=_("Ping trackback for tracback urls. Attn, it doesn't work if Entry is not visible."))
    trackbacked_sites = models.TextField(_('Trackback urls'), blank=True)

    tags = models.ManyToManyField(Tag, verbose_name='list of tags', blank=True)

    comment_count = models.IntegerField(_('Comment count'), default=0, editable=False)
    trackback_count = models.IntegerField(_('Trackback count'), default=0, editable=False)

    riddle = models.CharField(_('Riddle'), max_length=250, db_index=False, blank=True, help_text=_('Riddle for commenting this entry.'))
    answer = models.CharField(_('Answer'), max_length=50, db_index=False, blank=True, help_text=_("Riddle's answer. Ignore case."))

    related_contents = generic.GenericRelation(RelatedItem)

    private_objects = EntryPrivateManager()
    public_objects = EntryPublicManager()

    def __unicode__(self) :
        return self.title

    def trackback_array(self) :
        return self.trackback_set.order_by('create_date')

    def comment_array(self) :
        return self.comment_set.order_by('create_date')

    def get_absolute_url(self):
        return '%s/%s/%s/' % (settings.BLOG_BASE, self.create_date.strftime('%Y/%b/%d').lower(), self.slug)
    absolute_url = property(get_absolute_url)

    def get_month_url(self) :
        return '%s/%s/' % (settings.BLOG_BASE, self.create_date.strftime('%Y/%b').lower())
    month_url = property(get_month_url)

    def _get_day_url(self) :
        return '%s/%s/' % (settings.BLOG_BASE, self.create_date.strftime('%Y/%b/%d').lower())
    day_url = property(_get_day_url)

    def _create_month(self) :
        return '%4d/%02d' % (self.create_date.year, self.create_date.month)
    create_month = property(_create_month)

    def save(self):
        self.should_tb = self.trackback_now and self.visible and len(self.trackbacked_sites.strip()) > 0
        self.should_ping = self.ping_now and self.visible
        self.trackback_now = False
        self.ping_now = False
        super(Entry, self).save()
        Archive.objects.get_or_create(yearmonth='%4d%02d' % (self.create_date.year, self.create_date.month))
        if self.should_tb :
            pass #TODO implements it.
        if self.should_ping :
            ping_server_list = Pingsites.objects.all()
            for ping_server in ping_server_list :
                pass #TODO implements it.

    delete = delete_for_related


class Comment(models.Model) :
    entry = models.ForeignKey(Entry)

blog/templates/blog/comment_form.html
{% extends 'blog/entry_detail.html' %}
{% load i18n %}

  {% block comment_form %}
					<div id="comment_form">
						<form action="."　method="POST">
							<fieldset>
								<legend>{% trans 'add comment' %}</legend><br />
								{% if form.has_errors %}
								<h4>{% trans 'Please correct the following error' %}{{ form.error_dict|pluralize }}:</h4>
								{% endif %}
								<div class="form_label">
									<label for="id_author">{% trans 'Commentator' %}{% if form.author.errors %}<br /><span class="error">{{ form.author.errors|join:", " }}</span>{% endif %}</label>
								</div>
								<div class="form_input">{{ form.author }}</div>
								<div class="dummy">&nbsp;</div>
								<div class="form_label">
									<label for="id_url">{% trans 'URL' %}{% if form.url.errors %}<br /><span class="error">{{ form.url.errors|join:", " }}</span>{% endif %}</label>
								</div>
								<div class="form_input">{{ form.url }}</div>
								<div class="dummy">&nbsp;</div>
								<div class="form_label">
									<label for="id_body">{% trans 'body' %}{% if form.body.errors %}<br /><span class="error">{{ form.body.errors|join:", " }}</span>{% endif %}</label>
								</div>
								<div class="form_input">{{ form.body }}</div>
								<div class="dummy">&nbsp;</div>
								{% if object.riddle %}
								<h4>{{ object.riddle }}</h4>
								<div class="form_label">
									<label for="id_answer">{% trans 'answer' %}{% if form.answer.errors %}<br /><span class="error">{{ form.answer.errors|join:", " }}</span>{% endif %}</label>
								</div>
								<div class="form_input">{{ form.answer }}</div>
								<div class="dummy">&nbsp;</div>
								{% endif %}
								<input type="submit" class="form_button" value="{% trans 'Comment' %}" />
								<div class="dummy">&nbsp;</div>
							</fieldset>
						</form>
					</div>
  {% endblock %}

blog/templates/blog/entry_archive_day.html
{% extends 'blog/entry_list.html' %}

{% block title %}{{ day|date:"Y-m-d"}}{% endblock %}

blog/templates/blog/entry_archive_month.html
{% extends 'blog/entry_list.html' %}

{% block title %}{{ month|date:"Y-m"}}{% endblock %}

blog/templates/blog/entry_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load related_tags %}

{% block custom_js %}
  {% if user.is_staff %}
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/MochiKit.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Base.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Async.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Format.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/DOM.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Style.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Signal.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Iter.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Color.js"></script>
<script type="text/javascript" src="http://static.everes.net/media/js/MochiKit/Visual.js"></script>
<script language="JavaScript">
<!--
  var content_type_id = {{ blog_entry }};
  var object_id = {{ object.id }};
  var search_url = "/djblogkit/related/search/{{ blog_entry }}/{{ object.id }}/";
  var current_url = "/djblogkit/related/current/{{ blog_entry }}/{{ object.id }}/";
  var add_related_url = '/djblogkit/related/add/{{ blog_entry }}/{{ object.id }}/';
  var remove_related_url = '/djblogkit/related/remove/{{ blog_entry }}/{{ object.id }}/';
  var handle_search_result = function (result) {
	test = "";
    data = result.data;
    if(data.length > 0) {
        for(i=0;i < data.length;i++) {
            test += data[i];
        }
        test += "<div class='dummy' />";
    }
    $('related_contents_result').innerHTML = test;
  }
  function show_search_form() {
	set_current("");
    t = $('related_contents_form');
    appear(t);
  }
  function search() {
	$('current_related_contents').innerHTML = "";
    target_content_type_id = $('relatable_id').options[$('relatable_id').selectedIndex].value;
    keywords_value = strip($('keywords').value, " ");
    url = search_url + target_content_type_id + "/?keywords=" + keywords_value;
    query = {};
    d = loadJSONDoc(url, query);
    d.addCallbacks(handle_search_result);
  }
  var handle_add_result = function (result){
	if (result.result == false) {
        alert(result.message);
	} else {
        t = $('related_search_result_' + result.target_content_type_id + '_' + result.target_object_id);
        puff(t);
	}
  }
  var handle_current_result = function (result){
    if (result.result == false) {
	  alert(result.message);
    } else {
      tmp = "";
      data = result.data;
	  for(i=0;i < data.length;i++) {
	    tmp += data[i];
      }
      set_current(tmp);
    }
  }
  function set_current(html) {
	$('current_related_contents').innerHTML = html;
  }
  function get_current() {
    fade('related_contents_form');
	$('related_contents_result').innerHTML = "";
    d = loadJSONDoc(current_url);
    d.addCallbacks(handle_current_result);	
  }
  var handle_remove_result = function (result){
	if (result.result == false) {
      alert(result.message);
	} else {
      t = $('related_current_result_' + result.target_content_type_id + '_' + result.target_object_id);
      dropOut(t);
	}
  }
  function set_related(target_content_type_id, target_object_id) {
    query = {};
    url = add_related_url + "?target_content_type_id=" + target_content_type_id + "&target_object_id=" + target_object_id;
    d = loadJSONDoc(url, query);
    d.addCallbacks(handle_add_result);
  }
  function remove_related(target_content_type_id, target_object_id) {
    query = {};
    url = remove_related_url + "?target_content_type_id=" + target_content_type_id + "&target_object_id=" + target_object_id;
    d = loadJSONDoc(url, query);
    d.addCallbacks(handle_remove_result);
  }
-->
</script>
  {% endif %}
{% endblock %}

{% block content %}
{% get_related_objects with object of blog_entry as related_objects %}
    {% include 'blog/rdf.html' %}
					<h2>{{ object.title }}</h2>
					<div class="meta">
						<span class="date">{{ object.create_date|date:"F d, Y  H:i"}}</span>
						<span class="postedBy">Posted by <a href="#">{{ object.author }}</a></span>
					</div>
					<p>
						{% if related_objects %}
						{% for r in related_objects %}
						  {% if r.inline %}
						    {{ r.render_related }}
						  {% endif %}
						{% endfor  %}
						{% endif %}
						<div class="dummy"></div>
						{{ object.body }}
					</p>
					{% if related_objects %}
					{% for r in related_objects %}
					  {% if not r.inline %}
					    <div class="url">{% trans 'related item' %}-{{ forloop.counter }}: <a href="{{ r.get_absolute_url }}">{{ r }}</a></div>
					  {% endif %}
					{% endfor  %}
					{% endif %}
					<div class="url">perm link: <a href="{{ object.absolute_url }}">{{ object.absolute_url }}</a></div>
					<div class="url">trackback: {{ object.absolute_url }}/tbping/</div>
					<div class="additional">
						{% for comment in object.comment_array %}
						{% if forloop.first %}<h3>{% trans 'Comments' %}</h3>{% endif %}
						<div class="{% cycle comment_row1,comment_row2 %}">
							<div class="meta">
								<span class="date">{{ comment.create_date|date:"F d, Y  H:i"}}</span>
								<span class="postedBy">by {% if comment.url %}<a href="{{ comment.url }}">{% endif %}{{ comment.author }}{% if comment.url %}</a>{% endif %}</span>
							</div>
							<p>{{ comment.body|escape|linebreaks }}</p>
						</div>
						{% endfor %}
					</div>
					<div class="additional">
						{% for trackback in object.trackback_array %}
						{% if forloop.first %}<h3>{% trans 'Trackbacks' %}</h3>{% endif %}
						<div class="{% cycle comment_row1,comment_row2 %}">
							<div class="meta">
								<span class="date">{{ comment.create_date|date:"F d, Y  H:i"}}</span>
								<span class="postedBy">by <a href="{{ trackback.url }}">{{ trackback.blog_name }}</a></span>
							</div>

							<p>{{ comment.excerpt|escape|linebreaks }}</p>
						</div>
						{% endfor %}
					</div>
  {% if user.is_staff %}
{% load related_tags %}
<div id="related_contents_controller">
    <div id="related_contents_header">
	  <img src="/djblogkit/static/images/24-search.png" onClick="show_search_form();" alt="{% trans 'Joint new' %}" /> 
	  <img src="/djblogkit/static/images/24-current.png" onClick="get_current();" alt="{% trans 'Remove current' %}" />
	</div>
	<div id="related_contents_form">
        {% get_relatable_list as relatable_list %}
        <select id="relatable_id" class="related_contents_input">
            {% for relatable in relatable_list %}<option value="{{ relatable.content_type.id }}">{{ relatable.content_type.name }}</option>
            {% endfor %}
        </select>
        <input type="text" class="related_contents_input" id="keywords" value="" />
        <input type="button" value="{% trans 'Search' %}" onClick="search();" />
	</div>
	<div id="related_contents_result">
	</div>
    <div id="current_related_contents">
	</div>
</div>
  {% endif %}
  {% block comment_form %}
					<div id="comment_form">
						<form action="./add_comment/"　method="POST">
							<fieldset>
								<legend>{% trans 'add comment' %}</legend><br />
								<div class="form_label"><label for="id_author">{% trans 'Commentator' %}</label></div>
								<div class="form_input"><input type="text" id="id_author" name="author" /></div>
								<div class="dummy">&nbsp;</div>
								<div class="form_label"><label for="id_url">{% trans 'URL' %}</label></div>
								<div class="form_input"><input type="text" id="id_url" name="url" /></div>
								<div class="dummy">&nbsp;</div>
								<div class="form_label"><label for="id_body">{% trans 'body' %}</label></div>
								<div class="form_input"><textarea id="id_body" name="body" cols="35" rows="5"></textarea></div>
								<div class="dummy">&nbsp;</div>
								{% if object.riddle %}
								<h4>{{ object.riddle }}</h4>
								<div class="form_label"><label for="id_answer">{% trans 'answer' %}</label></div>
								<div class="form_input"><input type="text" id="id_answer" name="answer" /></div>
								<div class="dummy">&nbsp;</div>
								{% endif %}
								<input type="submit" class="form_button" value="{% trans 'Comment' %}" />
								<div class="dummy">&nbsp;</div>
							</fieldset>
						</form>
					</div>
  {% endblock %}
{% endblock %}

blog/templates/blog/entry_list.html
{% extends 'base.html' %}
{% load i18n blogfilter %}

{% block content %}
  {% for object in object_list %}
    {% include 'blog/rdf.html' %}
					<h2>{{ object.title }}</h2>
					<div class="meta">
						<span class="date">{{ object.create_date|date:"F d, Y  H:i"}}</span>
						<span class="postedBy">Posted by <a href="#">{{ object.author }}</a></span>
					</div>
					<div style="clear: both;"> </div>
					<p>{{ object.body|truncatelines:3 }}</p>
					<div class="meta">{% if object.has_3lines %}<a href="{{ object.absolute_url }}">read more...</a>{% endif %}</div>
					<div class="comments">
						{{ object.trackback_count }} trackbacks | {{ object.comment_count }} comments | <a href="{{ object.absolute_url }}#comment">View or Leave comments</a>
					</div>
　　{% endfor %}
{% endblock %}

blog/templates/blog/rdf.html
{% load blogfilter %}
<!--
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/"
     xmlns:dc="http://purl.org/dc/elements/1.1/">
<rdf:Description
    rdf:about="http://www.everes.net"
    trackback:ping="http://www.everes.net{{ object.get_absolute_url }}tbping"
    dc:title="{{ object.title }}"
    dc:identifier="http://www.everes.net{{ object.get_absolute_url }}"
    dc:description="{{ object.body|escape|truncatelines:5|to_oneline }}"
    dc:creator="{{ object.author }}"
    dc:date="{{ object.create_date|date:"Y-m-d" }}T{{ object.create_date|time:"H:i:s" }}+09:00" />
</rdf:RDF>
-->